# Default values for base-helm-chart.

base:
  name: "app-name"
  
  deploy:
    replicaCount: 1
    image: 
      repository: "base"
      tag: "0.0.1"
#      imagePullSecrets: regcred
    port:
      enable: true
      containerport: 80
      name: "http"
    # Only work if container port is enable
    healthcheck:
      enable: true
      path: "/"

    env: {}
# - name: NODE_ENV
#   value: 'production'
# - name: NODE_PORT
#   value: '8000'

    secrets: {}
#    - name: SECRET_NAME
#      secret_name: secret_name
#      secret_key: secret_key

#    resources:
#      limits:
#        memory: 512Mi
#      requests:
#        memory: 256Mi

  service:
    enable: true
    type: "ClusterIP"
    port: 80
    targetPort: 80
    protocol: "TCP"
  
# Need to enable service to allow ingress
  ingress:
    enable: true
    annotations: {}
    host: "myapp.com"
    path: "/"
    tls:
      enable: true
      issuer: "letsencrypt-issuer"

  flux:
    enable: true