{{ if .Values.base.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.base.name }}-svc"
spec:
  ports:
    - port: {{ .Values.base.service.port }}
      protocol: {{ .Values.base.service.protocol }}
      targetPort: {{ .Values.base.service.targetPort }}
  selector:
    app: "{{ .Values.base.name }}"
  type: "{{ .Values.base.service.type }}"
{{ end }}